version: "3"
services:

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /config/configuration.yaml:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: unless-stopped
    ports:
      - "8123:8123"
    privileged: true
    depends_on:
      - nginx-home

  nginx-home:
    image: nginx
    container_name: nginx-home
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d


  # nagios:
  #   container_name: nagios
  #   image: "manios/nagios:latest"
  #   ports:
  #     - "8080:80"
  #   environment:
  #     - NAGIOSADMIN_USER=${NAGIOS_USER}
  #     - NAGIOSADMIN_PASS=${NAGIOS_PASS}
  #   volumes:
  #     - nagiosetc:/opt/nagios/etc
  #     - nagiosvar:/opt/nagios/var

# volumes:
#   nagiosetc:
#   nagiosvar:
